export function exportToCSV(headers: string[], rows: any[][], filename: string) {
  try {
    const csvContent = [
      headers.join(','),
      ...rows.map(row => 
        row.map(val => {
          const str = String(val ?? '');
          // Escape quotes
          if (str.includes(',') || str.includes('"') || str.includes('\n')) {
            return `"${str.replace(/"/g, '""')}"`;
          }
          return str;
        }).join(',')
      )
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    console.error("Export to CSV failed:", error);
  }
}

export function exportReportToTXT(title: string, sections: Record<string, string | string[]>, filename: string) {
  try {
    let content = `====================================================\n`;
    content += `EXECUTIVE BI REPORT: ${title.toUpperCase()}\n`;
    content += `Generated by Talking Rabbitt Copilot\n`;
    content += `Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    content += `====================================================\n\n`;

    Object.entries(sections).forEach(([secTitle, secVal]) => {
      content += `## ${secTitle.toUpperCase()}\n`;
      if (Array.isArray(secVal)) {
        content += secVal.map(item => `- ${item}`).join('\n');
      } else {
        content += secVal;
      }
      content += `\n\n`;
    });

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.txt') ? filename : `${filename}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    console.error("Export report failed:", error);
  }
}
